### ISSUE TITLE
Errors when trying to install

### ISSUE THREAD

**Issue by sbuis** [SticsRPacks/SticsRPacks#1]
# Issue Name

Errors when trying to install

## Expected Behavior

Installation of SticsRpacks packages and dependent packages

## Current Behavior

Each time a dependent package is tried to be installed the process stopped with an error.

## Failure Information (for bugs)

Example: 

R code:  
```r
devtools::install_github("SticsRPacks/SticsRPacks")
```

Output:  
```r
Enter one or more numbers, or an empty line to skip updates:
1

package ‘******’ successfully unpacked and MD5 sums checked
Error: Failed to install 'SticsRPacks' from GitHub:
(converted from warning) cannot remove prior installation of package ‘*****’
```

## Context

* R version: 3.5.0
* RStudio version:  1.2.5001
* OS: Windows10
* Package dependencies version:

**Comment by VEZY** [comment]
These errors do not come from the `SticsRPacks` package, but from RStudio. It is a rather known issue for other packages (such as `tidyverse`). The problem is stated in the error: "cannot remove prior installation of package ‘*****’" means that R couldn't delete the current version of the package so it couldn't install the new one at the same place. 

The work-arounds can be to:

-  Terminate all R sessions running, including the one you are using right now because:
    * if R is running elsewhere and uses the package, a lock is placed on its folder so nothing can delete it; 
    * the state of the session you are using could be retreived from the previous session (terminate from the Session tab -> Terminate R);

- If the previous answer didn't work, install the package manually, e.g. `install.packages("remotes")` if you have issues with the `remotes` package, and see what is the output of the installation. If it works, you can proceed with the installation of `SticsRPacks`, if not, try to delete the previous installation manually from your library (you can find the path using `.libPaths()`).

- If the error of installation concerns one of our own packages, the error arise from the package itself, not from `SticsRPacks`. So open an issue on the package repo directly. Of course test by yourself to install it directly (e.g. `devtools::install_github("SticsRPacks/SticsOnR ")`) before. Or you can also try to build it yourself from the code to check for the errors.

Hope it helps!

PS: maybe we could add this information somewhere (to the readme?)

**Comment by VEZY** [comment]
Update from the furture: 
Alternatively, you can use `{pak}` instead of of `{devtools}`, and it will probably work better for the installation.

```r
install.packages("pak")
```

As of today (2023-01-06) the cran version of `{pak}` does not support well subdirectories though, which is problematic for Bayesian tools that has its package in a subdir. 

So you'll have to install the development version of pak instead:

```r
pak::pak_update(stream = "devel", force = TRUE)
```

The use pak to install `{SticsRPacks}` like so:

```r
pak::pkg_install("SticsRPacks/SticsRPacks")
```
